triggers:
  - type: meya.keyword
    properties:
        keyword: cars e class
name: cars_e_class
states:
    sedan_options:
        component: meya.cards
        properties:
            output: button_click
            elements:
              - title: '{{ cms.cars.title_e_class_sedan }}'
                text: '{{ cms.cars.text_e_class_sedan }}'
                image_url: https://s3-eu-west-1.amazonaws.com/mercedes-chatbot/mercedes/images/test-drive-form-cars/e_class_sedan.jpg
                buttons:
                  - text: '{{ cms.general.book_a_test_drive }}'
                    url: '{{ cms.links_test_drive_form.sedan_e_class }}'
                    webview_height_ratio: full
                    messenger_extensions: true
              - title: '{{ cms.cars.title_e_class_coupe }}'
                text: '{{ cms.cars.text_e_class_coupe }}'
                image_url: https://s3-eu-west-1.amazonaws.com/mercedes-chatbot/mercedes/images/test-drive-form-cars/e_class_coupe.jpg
                buttons:
                    url: '{{ cms.links_test_drive_form.coupe_e_class }}'
                    webview_height_ratio: full
                    messenger_extensions: true
              - title: '{{ cms.cars.title_e_class_cabriolet }}'
                text: '{{ cms.cars.text_e_class_cabriolet }}'
                image_url: https://s3-eu-west-1.amazonaws.com/mercedes-chatbot/mercedes/images/test-drive-form-cars/e_class_cabriolet.jpg
                buttons:
                  - text: '{{ cms.general.book_a_test_drive }}'
                    url: '{{ cms.links_test_drive_form.cabriolet_e_class }}'
                    webview_height_ratio: full
                    messenger_extensions: true
