triggers:
  - type: meya.regex
    properties:
        pattern: (\you live\b)|(\you from\b)|(\comes from\b)|(\come from\b)
states:
      random_text_state:
        component: meya.random_text
        properties:
            responses:
                - '{{ cms.faq.msg_from1 }}'
                - '{{ cms.faq.msg_from2 }}'
      go_to_main:
          flow: main_menu