triggers:
  - type: meya.keyword
    properties:
        keyword: recommend_suv_gle
name: recommend_suv_gle
states:
    recommended_text:
        component: meya.text
        properties:
            text: '{{ cms.recommend.msg_gle }}'
    car_options:
        component: meya.cards
        properties:
            output: button_click
            elements:
              - title: '{{ cms.recommend.title_gle }}'
                text: '{{ cms.recommend.text_gle }}'
                image_url: https://s3-eu-west-1.amazonaws.com/mercedes-chatbot/mercedes/images/test-drive-form-cars/gle_suv.jpg
                buttons:
                  - text: '{{ cms.general.book_a_test_drive }}'
                    url: '{{ cms.links_test_drive_form.suv_gle }}'
                    webview_height_ratio: full
                    messenger_extensions: true
                  - text: '{{ cms.general.visit_website }}'
                    url: '{{ cms.links_website_mb.suv_gle }}'
                  - text: '{{ cms.general.explore_more_models }}'
                    flow: explore_our_models_retry