triggers:
  - type: meya.keyword
    properties:
        keyword: sclassleaflet
name: s_class_leaflet_01
states:
    welcome:
        component: meya.text_buttons
        properties:
            text: "{{ cms.s_class_leaflet.msg_welcome }}"
            output: button_click
            buttons:
                - text: "{{ cms.main.btn_yes }}"
                  flow: s_class_leaflet_02
                - text: "{{ cms.main.btn_no }}"
                  action: next
    negative_state:
        component: meya.text_buttons
        properties:
            text: "{{ cms.s_class_leaflet.msg_not_interested }}"
            output: button_click
            buttons:
                - text: "{{ cms.main.btn_learn_more }}"
                  flow: s_class_leaflet_02
                - text: "{{ cms.s_class_leaflet.btn_leave_message }}"
                  action: next
    leave_message:
        component: meya.text
        properties:
            text: "{{ cms.s_class_leaflet.msg_customer_service }}"
