triggers:
  - type: meya.keyword
    properties:
        keyword: which suv
name: which_suv
states:
    confirmation:
        component: meya.text_buttons
        properties:
            text: '{{ cms.which_suv.msg_few_questions }}'
            mode: quick_reply
            output: button_click
            buttons:
              - text: '{{ cms.general.yes }}'
                flow: which_suv_ready
              - text: '{{ cms.general.no }}'
                flow: which_suv_unready
