triggers:
  - type: meya.keyword
    properties:
        keyword: wsuv_d_l_lux
name: wsuv_d_l_lux
states:
    question:
        component: meya.text_buttons
        properties:
            text: '{{ cms.which_suv.msg_is_spacious_important }}'
            mode: quick_reply
            output: button_click
            buttons:
              - text: '{{ cms.general.yes }}'
                flow: recommend_suv_gls
              - text: '{{ cms.general.no }}'
                flow: recommend_suv_gle
