triggers:
  - type: meya.keyword
    properties:
        keyword: wsuv_d_style
name: wsuv_d_style
states:
    question:
        component: meya.text_buttons
        properties:
            text: '{{ cms.which_suv.msg_which_best_suits_you }}'
            mode: quick_reply
            output: button_click
            buttons:
              - text: '{{ cms.general.luxurious }}'
                flow: wsuv_d_l_pax
              - text: '{{ cms.general.sporty }}'
                flow: wsuv_d_s_pax
              - text: '{{ cms.general.practical }}'
                flow: wsuv_d_p_pax
