triggers:
  - type: meya.keyword
    properties:
        keyword: wsuv_w_c_style
name: wsuv_w_c_style
states:
    question:
        component: meya.text_buttons
        properties:
            text: '{{ cms.which_suv.msg_which_best_suits_you }}'
            mode: quick_reply
            output: button_click
            buttons:
              - text: '{{ cms.general.luxurious }}'
                flow: wsuv_w_c_l_pax
              - text: '{{ cms.general.sporty }}'
                flow: wsuv_w_c_s_pax
              - text: '{{ cms.general.practical }}'
                flow: recommend_suv_gle_coupe
