triggers:
  - type: meya.keyword
    properties:
        keyword: wsuv_d_p_lux
name: wsuv_d_p_lux
states:
    question:
        component: meya.text_buttons
        properties:
            text: '{{ cms.which_suv.msg_interested_in_more_luxurious }}'
            mode: quick_reply
            output: button_click
            buttons:
              - text: '{{ cms.general.yes }}'
                flow: recommend_suv_gle
              - text: '{{ cms.general.no }}'
                flow: recommend_suv_glc
