triggers:
  - type: meya.keyword
    properties:
        keyword: wsuv_w_c_off
name: wsuv_w_c_off
states:
    question:
        component: meya.text_buttons
        properties:
            text: '{{ cms.which_suv.msg_are_you_an_explorer }}'
            mode: quick_reply
            output: button_click
            buttons:
              - text: '{{ cms.general.yes }}'
                flow: recommend_suv_g_class
              - text: '{{ cms.general.no }}'
                flow: recommend_suv_gle_coupe
